name: Timelane

on: [push]

jobs:
  macOS:
    name: "macOS"
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: set -o pipefail && xcodebuild -project TimelaneCore/TimelaneCore.xcodeproj -scheme TimelaneCore -enableCodeCoverage YES -sdk macosx -destination "arch=x86_64" test | xcpretty -c -r html --output logs/macOS.html
    - uses: actions/upload-artifact@v1
      with:
        name: build-logs=${{ github.run_id }}
        path: logs
